requires:
- name: "toolchain"
  category: "development"
  version: ">=0"
env:
- CGO_ENABLED=0
- PACKAGE_VERSION={{ .Values.version }}
prelude:
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/derailed/k9s
steps:
- |
   cd k9s && \
   make build && \
   cp execs/k9s /usr/bin && \
   upx /usr/bin/k9s

includes:
- /usr/bin/k9s