requires:
- name: "toolchain-go"
  category: "development"
  version: ">=0"
env:
{{$arch:=(default .Values.arch "amd64")}}
  - INSTALL_K3S_BIN_DIR="/usr/bin"
  - INSTALL_K3S_SELINUX_WARN=true
  - INSTALL_K3S_SKIP_START="true"
  - INSTALL_K3S_SKIP_ENABLE="true"
  - INSTALL_K3S_SKIP_SELINUX_RPM="true"
  {{ if eq $arch "arm" }}
  - ARCH=arm64
  {{ else }}
  - ARCH={{ $arch }}
  {{ end }}
steps:
  - curl -sfL https://get.k3s.io > installer.sh
  # Let the installer script install service files both for openrc and systemd:
  # https://github.com/k3s-io/k3s/blob/36645e7311e9bdbbf2adb79ecd8bd68556bc86f6/install.sh#L114-L122
  - touch /bin/systemctl && chmod +x /bin/systemctl
  - mkdir -p /etc/systemd/system/
  - bash installer.sh
  - bash installer.sh agent
  # Run again to create the openrc service files
  - rm /bin/systemctl
  - rm -rf /etc/systemd/system/
  - touch /sbin/openrc-run && chmod +x /sbin/openrc-run
  - bash installer.sh
  - rm -rf installer.sh
  - echo "{{ ( index .Values (print "checksum-" $arch) ) }}  /usr/bin/{{.Values.name}}" | sha256sum -w -c
  - chmod +x /usr/bin/{{.Values.name}}

includes:
- /usr/bin/{{.Values.name}}
- /etc/systemd/system/k3s*.service
- /etc/init.d/k3s*
