requires:
- name: "toolchain-go"
  category: "development"
  version: ">=0"
env:
{{$arch:=(default .Values.arch "amd64")}}
  - INSTALL_K3S_BIN_DIR="/usr/bin"
  - INSTALL_K3S_SELINUX_WARN=true
  - INSTALL_K3S_SKIP_START="true"
  - INSTALL_K3S_SKIP_ENABLE="true"
  - INSTALL_K3S_SKIP_SELINUX_RPM="true"
  {{ if eq $arch "arm" }}
  - ARCH=arm64
  {{ else }}
  - ARCH={{ $arch }}
  {{ end }}
steps:
  - curl -sfL https://get.k3s.io > installer.sh
  - bash installer.sh
  - bash installer.sh agent
  - rm -rf installer.sh
  - /bin/bash -c 'echo "{{ ( index .Values (print "checksum-" $arch) ) }} /usr/local/bin/{{.Values.name}}" | sha256sum -c'
  - chmod +x /usr/local/bin/{{.Values.name}}

includes:
- /usr/local/bin/{{.Values.name}}
- /etc/systemd/system/k3s*.service
- /etc/init.d/k3s*
