requires:
- name: "toolchain-go"
  category: "development"
  version: ">=0"
env:
  - INSTALL_K3S_BIN_DIR="/usr/bin"
  - INSTALL_K3S_SELINUX_WARN=true
  - INSTALL_K3S_SKIP_START="true"
  - INSTALL_K3S_SKIP_ENABLE="true"
  - INSTALL_K3S_SKIP_SELINUX_RPM="true"
  # Remove any possible "+N" from the end of the version. We only bump that to
  # avoid overwritting existing images when we want the package to be rebuilt.
  - INSTALL_K3S_VERSION=v{{ regexReplaceAll "\\+\\d+$" .Values.version "" }}+k3s1
  {{$arch:=(default "amd64" .Values.arch)}}
  {{ if eq $arch "arm" }}
  - ARCH=arm64
  {{ else }}
  - ARCH={{ $arch }}
  {{ end }}
steps:
  - curl -sfL https://get.k3s.io > installer.sh
  # Let the installer script install service files both for openrc and systemd:
  # https://github.com/k3s-io/k3s/blob/36645e7311e9bdbbf2adb79ecd8bd68556bc86f6/install.sh#L114-L122
  - touch /bin/systemctl && chmod +x /bin/systemctl
  - mkdir -p /etc/systemd/system/
  - bash installer.sh
  - bash installer.sh agent
  # Save the service files elsewhere because the next run will delete them
  - mkdir -p /service-files && cp /etc/systemd/system/k3s*.service /service-files/
  # Run again to create the openrc service files
  - rm /bin/systemctl
  - touch /sbin/openrc-run && chmod +x /sbin/openrc-run
  - bash installer.sh
  - rm -rf installer.sh
  - chmod +x /usr/bin/{{.Values.name}}
  # Put systemd service files back in place
  - mv /service-files/* /etc/systemd/system/

includes:
- ^/usr/bin/{{.Values.name}}
- ^/etc/systemd$
- ^/etc/systemd/system$
- ^/etc/systemd/system/k3s.*service$
- ^/etc/init.d/$
- ^/etc/init.d/k3s.*
