image: alpine
package_dir: "/package"
steps:
- mkdir -p /package/etc/systemd/system
- mkdir -p /package/etc/dracut.conf.d
- cp -rf tmp.mount /package/etc/systemd/system
- mkdir -p /package/usr/lib/dracut/modules.d
- cp -r 30cos-immutable-rootfs /package/usr/lib/dracut/modules.d
- cp -rfv conf/* /package/etc/dracut.conf.d
- cp -rfv 30cos-immutable-rootfs/cos-setup-*.service /package/etc/systemd/system
