{{ if eq .Values.version "0.23.1" }}
# edgevpn 0.23.x can only be built with golang 1.19.x
requires:
  - name: "toolchain-go-ubuntu"
    category: "development"
    version: "<1.20.0"
{{ else }}
requires:
  - name: "toolchain-go-ubuntu"
    category: "development"
    version: ">=0"
{{ end }}

prelude:
- mkdir go/src/github.com/${GITHUB_ORG}/ -p
- cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
env:
- GOPATH=/luetbuild/go/
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
- CGO_ENABLED=0
- PACKAGE_VERSION={{ .Values.tag }}
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
  cd go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/  && git checkout v"${PACKAGE_VERSION}" -b build && go build -ldflags="-w -s -X github.com/mudler/edgevpn/internal.Version=v$PACKAGE_VERSION" && mv {{.Values.name}} /usr/bin/
- upx -1 /usr/bin/{{.Values.name}}
- chmod +x /usr/bin/{{.Values.name}}
includes:
- /usr/bin/{{.Values.name}}
