image: alpine
package_dir: "/package"
steps:
  - mkdir -p /package/etc/mkinitfs/features.d
  - mkdir -p /package/etc/mkinitfs/
  - mkdir -p /package/usr/share/mkinitfs/
  - cp files/immucore.files /package/etc/mkinitfs/features.d/immucore.files
  - cp files/tpm.modules /package/etc/mkinitfs/features.d/tpm.modules
  - cp files/mkinitfs.conf /package/etc/mkinitfs/mkinitfs.conf
  - cp files/initramfs-init /package/usr/share/mkinitfs/initramfs-init
