name: "Create openrc services"
stages:
  initramfs:
    - name: "Create files"
      if: |
          grep -i alpine "/etc/os-release"
      files:
      - path: /etc/init.d/kairos-agent
        content: |
          #!/sbin/openrc-run

          depend() {
            provide kairos-agent
            after cos-setup-network
            use net
          }

          start() {
              kairos-agent start
              eend $?
          }
        permissions: 0755
        owner: 0
        group: 0
      - path: /etc/init.d/kairos-webui
        content: |
          #!/sbin/openrc-run

          depend() {
            provide kairos-webui
          }

          supervisor=supervise-daemon
          name="kairos-webui"
          command="kairos-agent webui"
          supervise_daemon_args="--stdout /var/log/kairos/webui.log --stderr /var/log/kairos/webui.log"
          pidfile="/run/${RC_SVCNAME}.pid"
          respawn_delay=5
          set -o allexport
          if [ -f /etc/environment ]; then source /etc/environment; fi
          set +o allexport

        permissions: 0755
        owner: 0
        group: 0
      - path: /etc/issue
        content: |


          ██╗  ██╗ █████╗ ██╗██████╗  ██████╗ ███████╗
          ██║ ██╔╝██╔══██╗██║██╔══██╗██╔═══██╗██╔════╝
          █████╔╝ ███████║██║██████╔╝██║   ██║███████╗
          ██╔═██╗ ██╔══██║██║██╔══██╗██║   ██║╚════██║
          ██║  ██╗██║  ██║██║██║  ██║╚██████╔╝███████║
          ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
                                                      

          Welcome to kairos (login with user: kairos, password: kairos)
          Kernel \r on an \m (\l)
        permissions: 0755
        owner: 0
        group: 0
