requires:
- name: "toolchain"
  category: "development"
  version: ">=0"
env:
- CGO_ENABLED=0
prelude:
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/helm/helm
steps:
- |
   cd helm && \
   make build && \
   cp bin/helm /usr/bin
includes:
- /usr/bin/helm