image: fedora

prelude:
- dnf install -y git python3 python3-pip binutils
- mkdir go/src/github.com/{{ ( index .Values.labels "github.owner" ) }}/ -p
- PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && cd go/src/github.com/{{ ( index .Values.labels "github.owner" ) }}/ && git clone --branch v${PACKAGE_VERSION} https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }}.git

env:
  - GITHUB_ORG=
steps:
  - pip install pyinstaller
  - pyinstaller go/src/github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }}/src/ukify/ukify.py -F
  - mv dist/ukify /usr/bin/
  - chmod +x /usr/bin/ukify
includes:
  - /usr/bin/ukify
