
{{ if eq .Values.arch "arm" }}
{{ else }}
requires:
- name: "toolchain"
  category: "development"
  version: ">=0"
prelude:
- PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && wget https://github.com/$GITHUB_OWNER/$GITHUB_REPO/releases/download/v$PACKAGE_VERSION/{{.Values.name}}-linux-{{.Values.arch}} -O earthly
env:
- GITHUB_OWNER={{ ( index .Values.labels "github.owner" ) }}
- GITHUB_REPO={{ ( index .Values.labels "github.repo" ) }}
steps:
- | 
   mv {{ .Values.name }} /usr/bin/{{ .Values.name }}
- chmod +x /usr/bin/{{ .Values.name }}
includes:
- /usr/bin/{{.Values.name}}
{{ end }}