requires:
  - name: "toolchain"
    category: "development"
    version: ">=0"

steps:
- mkdir -p /data/boot
- wget https://download.opensuse.org/repositories/devel:/ARM:/Factory:/Contrib:/OdroidC2/standard/aarch64/odroidc2-firmware-{{.Values.version}}.aarch64.rpm
- rpm2cpio odroidc2-firmware-{{.Values.version}}.aarch64.rpm | cpio -idmv
- mv boot/* /data/boot
package_dir: "/data/boot"

