image: "fedora:42"
package_dir: "/package"
prelude:
  - dnf update -y && dnf install -y gcc make bison flex openssl openssl-devel elfutils-libelf-devel bc kmod xxd wget xz dwarves python3 cpio perl gettext diffutils bash coreutils tar which bzip2 findutils m4 perl-interpreter perl-Carp perl-devel perl-generators make diffutils gawk binutils redhat-rpm-config hmaccalc gcc-c++ python3-devel zstd gcc-c++-aarch64-linux-gnu binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
  - PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && wget https://cdn.kernel.org/pub/linux/kernel/v${PACKAGE_VERSION%%.*}.x/linux-${PACKAGE_VERSION}.tar.xz
  - PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && tar xf linux-${PACKAGE_VERSION}.tar.xz
env:
  - PACKAGE_VERSION=${PACKAGE_VERSION%\-*}
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - ARCH=arm64
  - CROSS_COMPILE=aarch64-linux-gnu-
  {{else}}
  - ARCH=x86_64
  {{end}}
{{end}}
steps:
  - mkdir -p /package/boot
  - mkdir -p /package/lib/modules/${PACKAGE_VERSION}/
{{ if eq .Values.name "linux-tiny" }}
  - cd linux-${PACKAGE_VERSION} && make tinyconfig
# Merge our additional config options to support a decent kernel even if tiny
  - cd linux-${PACKAGE_VERSION} && ./scripts/kconfig/merge_config.sh .config ../tinyconfig.config
{{ else }}
  - cd linux-${PACKAGE_VERSION} && make defconfig
{{ end }}
  - cd linux-${PACKAGE_VERSION} && make kernelversion
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) Image
  {{ else }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) bzImage
  {{ end }}
{{ end }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) modules
  - cd linux-${PACKAGE_VERSION} && ZSTD_CLEVEL=19 INSTALL_MOD_PATH="/package" INSTALL_MOD_STRIP=1 make modules_install
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - cp linux-${PACKAGE_VERSION}/arch/arm64/boot/Image /package/boot/vmlinuz
  {{else}}
  - cp linux-${PACKAGE_VERSION}/arch/x86_64/boot/bzImage /package/boot/vmlinuz
  {{ end }}
{{ end }}

