{{if eq .Values.category "fips" }}
requires:
  - name: "toolchain-go-ubuntu"
    category: "fips"
    version: ">=0"
{{else}}
requires:
  - name: "toolchain-go-ubuntu"
    category: "development"
    version: ">=0"
{{end}}
prelude:
{{if eq .Values.category "fips" }}
  - apt-get update && apt-get install -y gcc
{{end}}
  - mkdir go/src/github.com/${GITHUB_ORG}/ -p
  - apt-get update && apt-get install -y gcc libssl-dev
  - cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
{{ if ne .Values.live "yes" }}
  - cd go/src/github.com/${GITHUB_ORG}/ && git checkout v"${PACKAGE_VERSION}" -b build
{{ end }}
env:
  - GOPATH=/luetbuild/go/
  - DEBIAN_FRONTEND=noninteractive
  - GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
{{if eq .Values.category "fips" }}
  - CGO_ENABLED=1
  - GOEXPERIMENT=boringcrypto
{{else}}
  - CGO_ENABLED=0
{{end}}

steps:
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
    mkdir -p /system/discovery && \
    cd go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/ && go build -o {{ .Values.binary_name }} ./cmd/discovery/main.go && mv {{ .Values.binary_name }} /system/discovery
  - chmod +x /system/discovery/{{ .Values.binary_name }}
{{if eq .Values.category "fips" }}
  - go tool nm /system/discovery/{{ .Values.binary_name }} | grep -i "FIPS_mode"
{{end}}
includes:
  - /system/discovery/{{ .Values.binary_name }}
