{{if or (eq .Values.category "fips") (eq .Values.category "fips-static")}}
requires:
  - name: "toolchain-go-ubuntu"
    category: "fips"
    version: ">=0"
{{else}}
requires:
  - name: "toolchain-go-ubuntu"
    category: "development"
    version: ">=0"
{{end}}
prelude:
{{if or (eq .Values.category "fips") (eq .Values.category "fips-static")}}
  - apt-get update && apt-get install -y gcc
{{end}}
  - mkdir go/src/github.com/${GITHUB_ORG}/ -p
  - apt-get update && apt-get install -y gcc libssl-dev
  - cd go/src/github.com/${GITHUB_ORG}/ && git clone https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
{{ if ne .Values.live "yes" }}
  - cd go/src/github.com/${GITHUB_ORG}/ && git checkout 3912abcec424521725ccd335181f2fde90510081 -b build
{{ end }}
env:
  - GOPATH=/luetbuild/go/
  - DEBIAN_FRONTEND=noninteractive
  - CGO_LDFLAGS="-ldl"
  - GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
{{if or (eq .Values.category "fips") (eq .Values.category "fips-static")}}
  - CGO_ENABLED=1
  - GOEXPERIMENT=boringcrypto
{{else}}
  - CGO_ENABLED=0
{{end}}

steps:
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    mkdir -p /system/discovery && \
    cd go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/ && go build -ldflags="{{with .Values.ldflags}}{{.}}{{end}}" -o {{ .Values.binary_name }}  ./cmd/discovery/main.go && mv {{ .Values.binary_name }} /system/discovery
  - chmod +x /system/discovery/{{ .Values.binary_name }}
{{if or (eq .Values.category "fips") (eq .Values.category "fips-static")}}
  {{ if .Values.arch }}
    {{ if eq .Values.arch "amd64" }}
  - go tool nm /system/discovery/{{ .Values.binary_name }} | grep -i "FIPS_mode"
    {{end}}
  {{end}}
{{end}}
includes:
  - /system/discovery/{{ .Values.binary_name }}
