requires:
- name: "{{.Values.name}}"
  category: "distro-kernels"
  version: ">=0"

copy:
# The toolkit is required in module-setup and embedded in the initramfs. 
- package: 
    category: "system"
    name: "elemental-cli"
    version: ">=0"
  source: "/usr/bin/elemental"
  destination: "/usr/bin/elemental"
- package: 
    category: "dracut"
    name: "immutable-rootfs"
    version: ">=0"
  source: "/package/."
  destination: "/"
{{ if or ( eq .Values.name "opensuse" ) }}
- package: 
    category: "dracut"
    name: "sysext"
    version: ">=0"
  source: "/package/."
  destination: "/"
{{ end }}
- package: 
    category: "dracut"
    {{ if or ( eq .Values.name "ubuntu-20-lts" ) ( eq .Values.name "ubuntu" ) ( eq .Values.name "ubuntu-22-lts" ) }}
    name: "network-compat"
    {{ else }}
    name: "network"
    {{ end }}
    version: ">=0"
  source: "/package/."
  destination: "/"
- package: 
    category: "dracut"
    name: "kcrypt"
    version: ">=0"
  source: "/package/."
  destination: "/"
- package: 
    category: "system"
    name: "kcrypt"
    version: ">=0"
  source: "/usr/bin/kcrypt"
  destination: "/usr/bin/kcrypt"
prelude:
# remove if any
- rm -rf /boot/initrd || true
includes:
- ^/boot|^/boot/.*
steps:
# Create initrd
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut -f "/boot/initrd-${kernel}" "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd
