image: "alpine"

steps:
- cp -rfv suc-upgrade.sh /usr/sbin/suc-upgrade && chmod +x /usr/sbin/suc-upgrade
# set the SUC_VERSION key in the script to the package version
- sed -i "s/SUC_VERSION=.*/SUC_VERSION=${PACKAGE_VERSION}/" /usr/sbin/suc-upgrade