image: "fedora:latest"
package_dir: "/package"
prelude:
  - dnf update -y && dnf install -y gcc make bison flex openssl openssl-devel elfutils-libelf-devel bc kmod xxd wget xz dwarves python3 cpio perl gettext diffutils bash coreutils tar which bzip2 findutils m4 perl-interpreter perl-Carp perl-devel perl-generators make diffutils gawk binutils redhat-rpm-config hmaccalc gcc-c++ python3-devel zstd gcc-c++-aarch64-linux-gnu binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
  - wget https://cdn.kernel.org/pub/linux/kernel/v${PACKAGE_VERSION%%.*}.x/linux-${PACKAGE_VERSION}.tar.xz
  - ls -lh
  - tar xf linux-${PACKAGE_VERSION}.tar.xz
env:
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - ARCH=arm64
  - CROSS_COMPILE=aarch64-linux-gnu-
  {{else}}
  - ARCH=x86_64
  {{end}}
{{end}}
steps:
  - mkdir -p /package/boot
  - mkdir -p /package/lib/modules/${PACKAGE_VERSION}/
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - cp configs/arm64.config linux-${PACKAGE_VERSION}/.config
  {{ else }}
  - cp configs/x86.config linux-${PACKAGE_VERSION}/.config
  {{ end }}
{{ end }}
  - cd linux-${PACKAGE_VERSION} && make olddefconfig
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - diff configs/arm64.config linux-${PACKAGE_VERSION}/.config || true
  {{ else }}
  - diff configs/x86.config linux-${PACKAGE_VERSION}/.config || true
  {{ end }}
{{ end }}
  - cd linux-${PACKAGE_VERSION} && make kernelversion
{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) Image
  {{ else }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) bzImage
  {{ end }}
{{ end }}
  - cd linux-${PACKAGE_VERSION} && make -j$(nproc) modules
  - cd linux-${PACKAGE_VERSION} && make install
  - cd linux-${PACKAGE_VERSION} && ZSTD_CLEVEL=19 make INSTALL_MOD_PATH="/package/" INSTALL_MOD_STRIP=1 modules_install
  - cp /boot/* /package/boot

