name: "Fix home directory permissions (kairos issue #2797)"
stages:
  initramfs.after:
    - name: "Fix permissions"
      commands:
        - |
          # Iterate over users in /etc/passwd and chown their directories
          awk -F: '$3 >= 1000 && $6 ~ /^\/home\// {print $1, $6}' /etc/passwd | while read -r user homedir; do
              if [ -d "$homedir" ]; then  # Check if the home directory exists
                  echo "Changing ownership of $homedir to $user"
                  chown -R "$user":"$user" "$homedir"
              else
                  echo "Directory $homedir does not exist for user $user"
              fi
          done
