# Rootfs Kairos OEM configuration file
#
# This file is part of Kairos and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Rootfs Layout Settings for UKI"
stages:
  rootfs:
    - if: '[ -e "/run/cos/uki_mode" ] && [ ! -e "/dev/disk/by-label/UKI_ISO_INSTALL" ]'
      name: "Layout configuration for UKI boot"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_PERSISTENT:/usr/local"
        RW_PATHS: "/var /etc /srv"
        OVERLAY: "tmpfs:25%"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/modprobe.d
          /etc/rancher
          /etc/sysconfig
          /etc/runlevels
          /etc/ssh
          /etc/ssl/certs
          /etc/iscsi
          /etc/zfs
          /etc/cni
          /etc/kubernetes
          /home
          /opt
          /root
          /snap
          /var/snap
          /usr/libexec
          /var/log
          /var/lib/containerd
          /var/lib/extensions
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/snapd
          /var/lib/wicked
          /var/lib/longhorn
          /var/lib/cni
          /var/lib/dbus
          /usr/share/pki/trust
          /usr/share/pki/trust/anchors
          /var/lib/ca-certificates
    - if: '[ -e "/run/cos/uki_mode" ] && [ -e "/dev/disk/by-label/UKI_ISO_INSTALL" ]'
      # omit everything on installer, just set the ephemeral paths
      name: "Layout configuration for UKI installer"
      environment_file: /run/cos/cos-layout.env
      environment:
        RW_PATHS: "/var /etc /srv /home"
        OVERLAY: "tmpfs:25%"