name: "Default network configuration"
stages:
  rootfs.before:
    - name: "Enable systemd-network config files for DHCP" # Needed if systemd-networkd runs in the initramfs!
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      directories:
        - path: "/etc/systemd/network/" # doesnt exist on initramfs
          permissions: 0775
          owner: 0
          group: 0
      files:
        - path: /etc/systemd/network/20-dhcp.network
          permissions: 0644
          owner: 0
          group: 0
          content: |
            [Match]
            Name=en*
            [Network]
            DHCP=yes
            [DHCP]
            ClientIdentifier=mac
        - path: /etc/systemd/network/20-dhcp-legacy.network
          permissions: 0644
          owner: 0
          group: 0
          content: |
            [Match]
            Name=eth*
            [Network]
            DHCP=yes
            [DHCP]
            ClientIdentifier=mac
      commands:
        - networkctl reload # make sure it reloads our config files
  initramfs:
    - name: "Enable systemd-network config files for DHCP"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      files:
        - path: /etc/systemd/network/20-dhcp.network
          permissions: 0644
          owner: 0
          group: 0
          content: |
            [Match]
            Name=en*
            [Network]
            DHCP=yes
            [DHCP]
            ClientIdentifier=mac
        - path: /etc/systemd/network/20-dhcp-legacy.network
          permissions: 0644
          owner: 0
          group: 0
          content: |
            [Match]
            Name=eth*
            [Network]
            DHCP=yes
            [DHCP]
            ClientIdentifier=mac
      commands:
        - networkctl reload # make sure it reloads our config files
    - name: "Disable NetworkManager and wicked"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      systemctl:
        disable:
          - NetworkManager
          - wicked
    - name: "Enable systemd-network and systemd-resolved"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      systemctl:
        enable:
          - systemd-networkd
          - systemd-resolved
    - name: "Link /etc/resolv.conf to systemd resolv.conf"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ] && [ -f /etc/hosts ]'
      commands:
        - rm /etc/resolv.conf
        - ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
  boot:
    - name: "Reload systemd-networkd config"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      commands:
        - networkctl reload # make sure it reloads our config files
  fs:
    - name: "Reload systemd-networkd config"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      commands:
        - networkctl reload # make sure it reloads our config files
#     dns:
#      path: /etc/resolv.conf
#      nameservers:
#      - 8.8.8.8
