name: "sysext"
stages:
  fs.after:
    - name: "Default sysext extensions dirs"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      directories:
        - path: /etc/extensions
        - path: /run/extensions
        - path: /var/lib/extensions
        - path: /usr/lib/extensions
        - path: /usr/local/lib/extensions
  initramfs:
    - name: "systemd-sysext initramfs settings"
      if: '[ "$(kairos-agent state get kairos.init)" == "systemd" ]'
      systemctl:
        enable:
          - systemd-sysext
