stages:
  initramfs.before:
    - name: "Blacklist bpfilter on Alpine ( bug: https://github.com/kairos-io/kairos/issues/277 )"
      if: '[ "$(kairos-agent state get kairos.init)" == "openrc" ]'
      commands:
        - echo "install bpfilter /bin/false" > /etc/modprobe.d/blacklist_bpfilter.conf
