name: "Start installer on tty1"
stages:
  initramfs:
    - if: grep -q "nodepair.enable" /proc/cmdline && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos
        - systemctl enable kairos-webui
    - if: |
        grep -q "nodepair.enable" /proc/cmdline && [ -f /run/cos/uki_install_mode ] && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos
        - systemctl enable kairos-webui
    # Starts installer on boot for openRC based systems
    - if: grep -q "nodepair.enable" /proc/cmdline && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - sed -i -e 's/tty1.*//g' /etc/inittab
        - echo "tty1::respawn:/usr/bin/kairos-agent install tty1" >> /etc/inittab
    # Starts installer on boot for systemd based systems
    - if: |
        grep -q "interactive-install" /proc/cmdline && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos-interactive
    - if: |
        grep -q "interactive-install" /proc/cmdline && [ -f /run/cos/uki_install_mode ] && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos-interactive
    # Starts installer on boot for openRC based systems
    - if: grep -q "interactive-install" /proc/cmdline && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - sed -i -e 's/tty1.*//g' /etc/inittab
        - echo "tty1::respawn:/usr/bin/kairos-agent interactive-install --shell tty1" >> /etc/inittab
  boot:
    - if: |
        [ "$(kairos-agent state get boot)" == "livecd_boot" ] && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - rc-service kairos-webui start
    - if: | 
        [ "$(kairos-agent state get boot)" == "livecd_boot" ] && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl start kairos-webui
    - if: |
        [ -f /run/cos/uki_install_mode ] && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl start kairos-webui
