name: "Start installer on tty1"
stages:
  initramfs:
    # Start installer if we get the nodepair.enable cmdline and NOT the interactive-install cmdline as we can have both
    # and we dont want to trigger both
    # Works in livecd or uki install mode
    - if: grep -q "nodepair.enable" /proc/cmdline && grep -vq "interactive-install" && ([ "$(kairos-agent state get boot)" == "livecd_boot" ] || [ -f /run/cos/uki_install_mode ]) && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos
        - systemctl enable kairos-webui
    # Starts installer on boot for openRC based systems
    - if: grep -q "nodepair.enable" /proc/cmdline && grep -vq "interactive-install" && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - sed -i -e 's/tty1.*//g' /etc/inittab
        - echo "tty1::respawn:/usr/bin/kairos-agent install tty1" >> /etc/inittab
    # Starts interactive installer on boot for systemd based systems in livecd or uki install mode
    - if: |
        grep -q "interactive-install" /proc/cmdline && ([ "$(kairos-agent state get boot)" == "livecd_boot" ] || [ -f /run/cos/uki_install_mode ]) && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl stop kairos
        - systemctl disable kairos
        - systemctl disable getty@tty1
        - systemctl stop getty@tty1
        - systemctl mask getty@tty1
        - systemctl enable kairos-interactive
    # Starts installer on boot for openRC based systems
    - if: grep -q "interactive-install" /proc/cmdline && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - sed -i -e 's/tty1.*//g' /etc/inittab
        - echo "tty1::respawn:/usr/bin/kairos-agent interactive-install --shell tty1" >> /etc/inittab
  boot:
    - if: |
        [ "$(kairos-agent state get boot)" == "livecd_boot" ] && [ "$(kairos-agent state get kairos.init)" == "openrc" ]
      commands:
        - rc-service kairos-webui start
    - if: | 
        ([ "$(kairos-agent state get boot)" == "livecd_boot" ] || [ -f /run/cos/uki_install_mode ]) && [ "$(kairos-agent state get kairos.init)" == "systemd" ]
      commands:
        - systemctl start kairos-webui