image: registry.opensuse.org/opensuse/leap:15.4

prelude:
- zypper ref

{{ if .Values.arch }}
  {{ if eq .Values.arch "arm64" }}
steps:
- zypper in grub2-arm64-efi shim-susesigned
includes:
- usr/share/grub2/arm64-efi/
- usr/share/efi/.*/*.efi
- usr/share/efi/.*/*.der
  {{else}}
steps:
- zypper in grub2-x86_64-efi shim-susesigned
includes:
- usr/share/grub2/x86_64-efi/
- usr/share/efi/.*/*.efi
- usr/share/efi/.*/*.der
  {{end}}
{{end}}