{{if eq .Values.category "fips" }}
requires:
  - name: "toolchain-go-ubuntu"
    category: "fips"
    version: ">=0"
{{else}}
requires:
  - name: "toolchain-go-ubuntu"
    category: "development"
    version: ">=0"
{{end}}
prelude:
  - apt-get update && apt-get install -y npm gcc
  - mkdir /go/src/github.com/${GITHUB_ORG}/ -p
  - PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && cd /go/src/github.com/${GITHUB_ORG}/ && git clone --branch v${PACKAGE_VERSION} https://github.com/${GITHUB_ORG}/{{ .Values.name }}.git
env:
  - GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
  - HUGO_VERSION=0.110.0
{{if eq .Values.category "fips" }}
  - CGO_ENABLED=1
  - GOEXPERIMENT=boringcrypto
  # Because we don't track the compiled-with version on the agent we need to keep the symbols in order to checks FIPS compliance
  - LDFLAGS="-w -X github.com/kairos-io/kairos/v2/internal/common.VERSION=v${PACKAGE_VERSION}"
{{else}}
  - CGO_ENABLED=0
  - LDFLAGS="-s -w -X github.com/kairos-io/kairos/v2/internal/common.VERSION=v${PACKAGE_VERSION}"
{{end}}
copy:
  - package:
      category: "static"
      name: "kairos-docs"
      version: ">=0"
    source: "/usr/share/doc/kairos"
    destination: "/kairos-docs/"
steps:
  # Docs for webui, copy them from the package
  - mkdir -p /go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/internal/webui/public/local
  - cp -r /kairos-docs/* /go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/internal/webui/public/local/
  # Deps for webui
  - cd /go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/internal/webui/public && npm install
  # Now for the real binary with everything bundled!
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    cd /go/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/ && \
    go build -o /usr/bin/{{ .Values.name }} -ldflags="${LDFLAGS}"
  - chmod +x /usr/bin/{{.Values.name}}
{{if eq .Values.category "fips" }}
  - go tool nm /usr/bin/{{.Values.name}} | grep -i "FIPS_mode"
{{end}}
includes:
  - /usr/bin/{{.Values.name}}
