requires:
- name: "toolchain-go-ubuntu"
  category: "development"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- CGO_ENABLED=0
- PACKAGE_VERSION={{ .Values.tag }}
prelude:
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/containerd/nerdctl
steps:
- |
   cd nerdctl && \
   make binaries && \
   make BINDIR=/usr/bin install && \
   upx -1 /usr/bin/nerdctl
includes:
- /usr/bin/nerdctl