
image: {{.Values.image}}

{{if eq .Values.image "opensuse"}}
{{ if eq .Values.arch "arm64" }}
prelude:
- zypper in -y grub2-arm64-efi grub2
{{ else if eq .Values.arch "arm" }}

{{ else }}
prelude:
- zypper in -y grub2-i386-pc grub2-x86_64-efi grub2
{{ end }}
{{end}}

steps:
- mkdir /grub-artifacts
  {{if .Values.distribution}}
    {{if eq .Values.distribution "opensuse"}}
- cp -rf /usr/share/grub2/* /grub-artifacts
    {{else}}
- cp -rfL /usr/lib/grub/* /grub-artifacts
    {{end}}
  {{end}}

package_dir: /grub-artifacts