image: registry.opensuse.org/opensuse/leap:15.4

steps:
- mkdir -p /data/{boot,usr}
- PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && wget https://download.opensuse.org/ports/aarch64/tumbleweed/repo/oss/aarch64/u-boot-rpiarm64-$PACKAGE_VERSION.aarch64.rpm
- PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && rpm2cpio u-boot-rpiarm64-$PACKAGE_VERSION.aarch64.rpm | cpio -idmv
- mv usr/share/doc /data
- mv usr/share/licenses /data
- mv usr/* /data
- mv boot/vc/* /data
- rm -rf /data/boot
- rm -rf /data/usr
- rm -rf /data/share

package_dir: "/data"
