name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions: read-all
jobs:
  call-workflow:
    uses: kairos-io/kairos/.github/workflows/reusable-linting.yaml@d17464a24dd6eaba061042adff9fb29aa8236c5c  # v4.3.0
    with:
      yamldirs: ".github/workflows/"
      is-go: false
